# Generated by Django 4.2.13 on 2024-06-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('customer', models.CharField(max_length=120)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
